<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms and Conditions - AI Mailer</title>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root { --primary: #6366f1; --dark: #0f172a; --light: #f8fafc; }
        body { font-family: 'Plus Jakarta Sans', sans-serif; background-color: var(--light); color: #334155; line-height: 1.7; }
        .legal-container { max-width: 800px; margin: 80px auto; padding: 60px; background: #fff; border-radius: 32px; box-shadow: 0 20px 40px rgba(0,0,0,0.03); }
        h1 { font-weight: 800; color: var(--dark); margin-bottom: 40px; }
        h4 { font-weight: 700; color: var(--dark); margin-top: 30px; margin-bottom: 15px; }
        .back-link { display: inline-flex; align-items: center; color: var(--primary); text-decoration: none; font-weight: 600; margin-bottom: 30px; transition: 0.3s; }
        .back-link:hover { transform: translateX(-5px); }
        .back-link i { margin-right: 8px; }
        p, li { color: #64748b; }
        .last-updated { font-size: 0.85rem; color: #94a3b8; margin-bottom: 20px; text-transform: uppercase; letter-spacing: 0.05em; }
    </style>
</head>
<body>

<div class="container">
    <div class="legal-container animate__animated animate__fadeIn">
        <a href="index.php" class="back-link"><i class="fas fa-arrow-left"></i> Back to AI Mailer</a>
        <div class="last-updated">Last Updated: April 22, 2026</div>
        <h1>Terms and Conditions</h1>
        
        <p>By accessing or using AI Mailer, you agree to comply with and be bound by the following terms and conditions of use.</p>

        <h4>1. Use of Service</h4>
        <p>You agree to use AI Mailer only for lawful purposes. You are responsible for all content sent via your account and must comply with anti-spam laws (like CAN-SPAM or GDPR) in your jurisdiction.</p>

        <h4>2. Account Security</h4>
        <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</p>

        <h4>3. Prohibited Content</h4>
        <p>You may not use AI Mailer to send any content that is offensive, illegal, or that violates the rights of third parties. Our automated systems may scan and flag content for review if abuse is suspected.</p>

        <h4>4. AI Generation</h4>
        <p>Content generated by our AI agent depends on the third-party providers you choose to connect. AI Mailer is not responsible for any inaccuracies or unintended results generated by these third-party services.</p>

        <h4>5. Termination</h4>
        <p>We reserve the right to suspend or terminate your access to the service at our sole discretion, without notice, if you breach these terms.</p>

        <h4>6. Limitation of Liability</h4>
        <p>AI Mailer is provided "as is". In no event will we be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.</p>

        <h4>7. Contact Us</h4>
        <p>If you have any questions about these Terms and Conditions, please contact us at support@loopstech.com.</p>
    </div>
</div>

</body>
</html>
